import React from "react";
import Article from "Components/Article/Article";
import Link from "Components/Link/Link";
import Paragraph from "Components/Paragraph/Paragraph";
import isEmpty from "Utils/isEmpty";
import IPostModel from "Types/IPostModel";
import IResult from "Types/IResult";

interface IProps {
  newPost: IPostModel | null;
  posts?: IPostModel[];
  socket: SocketIOClient.Socket;
}

export default class ArchivePage extends React.Component<IProps> {
  public render() {
    const { newPost, posts } = this.props;
    return (
      <Article>
        <Paragraph>
          "Архив" is under construction.
        </Paragraph>
        <Paragraph>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent mattis venenatis malesuada. Aenean vitae bibendum risus. Aliquam nunc leo, congue vitae rhoncus eu, lacinia vel turpis. Sed sollicitudin tincidunt neque eget vehicula. Donec pretium purus lacus, ut ullamcorper nibh rhoncus in. Proin non mollis neque. Vivamus commodo suscipit erat, mollis fringilla lorem lacinia vitae. Donec egestas eros vel augue ullamcorper venenatis. Nulla ut rhoncus tortor, et maximus dui. Suspendisse facilisis tincidunt lacus sed tincidunt. Donec tellus erat, sodales non egestas eget, scelerisque non nibh. Maecenas orci augue, porttitor at tellus at, laoreet aliquet justo. Aenean non ultrices est.</Paragraph>
        <Paragraph>Nullam accumsan eget felis at pretium. Cras placerat gravida urna, in imperdiet ligula consequat a. Nullam magna lectus, sagittis non neque sed, euismod pellentesque neque. In non neque eget velit vestibulum ultrices. Mauris dapibus condimentum lectus, at suscipit turpis lacinia at. Phasellus varius molestie metus faucibus consequat. Nulla eget risus nec dolor fermentum molestie et non ligula.</Paragraph>
        <Paragraph>Fusce vulputate finibus efficitur. Ut sed nunc mattis, scelerisque justo at, congue neque. Nullam egestas mi ut fringilla egestas. Mauris tempus ac massa quis vestibulum. Fusce pellentesque sapien eget urna placerat, vitae tempus nisi convallis. Vestibulum varius, nisl in egestas porta, magna nisi posuere lorem, quis gravida mi mi ut massa. Nulla ut nisl in ipsum semper ultrices eu ac ex. Suspendisse rutrum vitae nisl luctus consequat. Cras sed arcu quis turpis rhoncus pharetra dapibus at ante. Integer ac nibh tristique, venenatis leo eu, pellentesque leo. Donec egestas imperdiet turpis eu porttitor. Aenean non commodo massa. Pellentesque blandit, massa sed pellentesque auctor, tortor ligula convallis neque, ut bibendum lectus odio id quam.</Paragraph>
        <Paragraph>Praesent lorem leo, gravida quis orci nec, dignissim hendrerit ante. Proin et lorem eu metus vestibulum dignissim ac ullamcorper mi. Nunc vel volutpat augue, quis tristique massa. Integer sit amet orci metus. Suspendisse vitae rhoncus sapien. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aliquam laoreet eros sed urna suscipit, pretium efficitur nunc maximus. Maecenas aliquet a ex vitae aliquet. Nunc dapibus viverra lectus at egestas. Vivamus pharetra, risus sed vulputate ullamcorper, lorem eros malesuada ipsum, in feugiat elit purus ut tellus. Maecenas egestas felis id diam aliquam, in convallis dui dignissim. Aliquam et nisi quis lorem lacinia ultrices ac a ipsum. Pellentesque massa nisl, ultricies sollicitudin commodo sit amet, semper nec augue. Proin nunc ligula, suscipit et egestas quis, vestibulum eget orci. Sed at augue tempor, vehicula nibh non, gravida ligula. Sed iaculis risus vel tortor commodo ultrices.</Paragraph>
        <Paragraph>Curabitur consequat nibh quam. Vestibulum feugiat, massa vitae consectetur pulvinar, ipsum massa maximus lectus, in varius dui massa nec sapien. Etiam fringilla, lorem aliquet auctor posuere, dui justo pellentesque nisi, quis vestibulum augue lectus elementum quam. Mauris vehicula erat eleifend odio lobortis tincidunt. Aliquam erat volutpat. Cras ut lorem laoreet, faucibus nisi in, viverra turpis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Phasellus luctus massa posuere finibus auctor. Mauris sed imperdiet augue. Vivamus quis suscipit libero.</Paragraph>
        <Paragraph>Integer condimentum, ligula at porta ornare, neque ante blandit enim, id rutrum velit nulla nec enim. Phasellus mattis libero a enim ultricies, eu viverra erat venenatis. Nulla et placerat ligula. Aenean faucibus ligula justo, eu tempus quam volutpat gravida. Phasellus sit amet lectus id turpis pharetra placerat. Mauris mi libero, scelerisque sit amet ligula ut, semper eleifend nulla. Vivamus sollicitudin fermentum dictum. Fusce in tellus eget purus rhoncus elementum. Proin nulla elit, ultrices iaculis lorem at, porta porttitor lacus. Phasellus sed aliquam magna. Donec vitae venenatis nibh. Suspendisse magna mauris, accumsan at mi eget, mollis luctus nisl. Vivamus eu dui non nibh interdum dapibus. Praesent tristique tellus tempor congue congue. Mauris tincidunt cursus mollis. Pellentesque non egestas nibh, sit amet viverra est.</Paragraph>
        <Paragraph>Aenean ullamcorper eros ipsum, eget ornare magna dignissim at. Mauris bibendum, erat in ornare luctus, purus metus vehicula lacus, nec auctor erat orci elementum ligula. Phasellus vel ultrices ipsum. Proin nec elit sit amet augue dapibus faucibus eget at sem. Etiam eu sagittis orci. Suspendisse varius felis eget sem pretium, nec eleifend nibh efficitur. Praesent ullamcorper massa vitae justo sagittis semper. Duis aliquam justo dolor, nec tristique massa congue eu. Fusce accumsan neque sed quam ultrices, vel vestibulum metus fermentum.</Paragraph>
        <Paragraph>Curabitur at sapien sed dui cursus tristique. Quisque consequat, risus a semper sollicitudin, nibh dolor ultricies mauris, sed gravida lectus lorem id turpis. Maecenas fermentum lacus mauris, eget dictum lorem cursus in. Donec sollicitudin, ante ullamcorper ullamcorper lobortis, ligula orci scelerisque ex, id consectetur lectus nisi quis augue. Donec sit amet consectetur erat. Donec malesuada elit nec metus condimentum venenatis. Ut non placerat tellus. Nam viverra tellus sed vestibulum tempus. Praesent non felis id augue pretium vehicula. Curabitur sodales metus tristique justo viverra interdum. Phasellus turpis quam, porta eu imperdiet a, fermentum eu lorem. Cras non quam ut libero aliquam mattis. Phasellus vestibulum eros quis nisl tincidunt cursus. Nulla eu lacinia velit. Nulla varius, sem ac interdum molestie, odio quam aliquet purus, id interdum nulla sapien ut magna.</Paragraph>
        <Paragraph>Duis nec lobortis lorem, ac pellentesque mi. Maecenas nisi nulla, ornare nec nibh sed, dapibus mollis risus. Proin non ante lectus. Mauris accumsan consequat est luctus volutpat. Maecenas faucibus mollis tristique. Nullam eros libero, vehicula sit amet nulla vel, posuere ullamcorper lacus. Integer aliquet nisl sed justo consequat facilisis. Quisque et tristique velit. Donec et egestas augue. Integer in neque sed tellus lobortis convallis sed scelerisque elit.</Paragraph>
        <Paragraph>Mauris orci turpis, posuere imperdiet ullamcorper a, placerat eget orci. Proin rutrum maximus risus, eget rhoncus est bibendum non. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nulla gravida sodales sapien feugiat fringilla. Suspendisse gravida nibh id venenatis dapibus. Maecenas ac scelerisque ligula, sit amet pharetra ligula. Pellentesque tempus diam lectus, eget convallis purus ullamcorper at. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam sem elit, accumsan eu varius et, scelerisque at nisi. Mauris luctus nec felis id posuere. Fusce venenatis interdum tortor, ac porttitor metus dapibus in. Praesent porttitor pretium pellentesque. </Paragraph>
      </Article>
    );
  }
}